webtalk_init -webtalk_dir C:/Users/dell/Desktop/DSY_SOLUTIONS/project_1/project_1.sim/sim_1/synth/func/xsim/xsim.dir/test_func_synth/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Apr 11 14:58:55 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "e6ac8d3d-3ee1-4958-9237-3fa376ffaa35" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "3a24a41b10fc4140876edd293100f1a1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1896 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "14" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "5.73_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "1128764_KB" -context "xsim\\usage"
webtalk_transmit -clientid 4005223873 -regid "" -xml C:/Users/dell/Desktop/DSY_SOLUTIONS/project_1/project_1.sim/sim_1/synth/func/xsim/xsim.dir/test_func_synth/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/dell/Desktop/DSY_SOLUTIONS/project_1/project_1.sim/sim_1/synth/func/xsim/xsim.dir/test_func_synth/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/dell/Desktop/DSY_SOLUTIONS/project_1/project_1.sim/sim_1/synth/func/xsim/xsim.dir/test_func_synth/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
